### ISSUE TITLE
Non-string features in retrieved datasets cause errors late in the training process

### ISSUE THREAD

**Issue by neubig** [neulab/prompt2model#265]
I selected the `sst2` dataset as a dataset, and it has labels that are integers. I went through most of the rest of the pipeline, but then encountered the following error when training started.

Basically, it seems that integer features are not allowed. Better behaviors would be:
1. Allow integer labels (by looking up the label mapping that comes with the dataset and changing the integers into strings)
2. If "1." is not possible, at least fail earlier when the user selects an integer feature as the input or output

```
Starting training.
Traceback (most recent call last):
  File "/Users/gneubig/anaconda3/envs/prompt2model/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/gneubig/anaconda3/envs/prompt2model/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/gneubig/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/gneubig/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/gneubig/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/gneubig/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/gneubig/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/gneubig/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/gneubig/work/prompt2model/cli_demo.py", line 435, in <module>
    main()
  File "/Users/gneubig/work/prompt2model/cli_demo.py", line 367, in main
    trained_model, trained_tokenizer = trainer.train_model(
  File "/Users/gneubig/work/prompt2model/prompt2model/model_trainer/generate.py", line 304, in train_model
    concatenated_training_dataset = concatenate_datasets(training_datasets)
  File "/Users/gneubig/anaconda3/envs/prompt2model/lib/python3.10/site-packages/datasets/combine.py", line 182, in concatenate_datasets
    return _concatenate_map_style_datasets(dsets, info=info, split=split, axis=axis)
  File "/Users/gneubig/anaconda3/envs/prompt2model/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 5829, in _concatenate_map_style_datasets
    _check_if_features_can_be_aligned([dset.features for dset in dsets])
  File "/Users/gneubig/anaconda3/envs/prompt2model/lib/python3.10/site-packages/datasets/features/features.py", line 2083, in _check_if_features_can_be_aligned
    raise ValueError(
ValueError: The features can't be aligned because the key output_col of features {'input_col': Value(dtype='string', id=None), 'output_col': Value(dtype='int64', id=None), 'model_input': Value(dtype='string', id=None), 'model_output': Value(dtype='string', id=None)} has unexpected type - Value(dtype='int64', id=None) (expected either Value(dtype='string', id=None) or Value("null").
```

**Comment by neubig** [comment]
I believe this is fixed.
