### ISSUE TITLE
KeyError in model name lookup

### ISSUE THREAD

**Issue by neubig** [neulab/prompt2model#270]
When retrieving a model, I'm getting a KeyError:

```
Retrieving model...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/gneubig/work/prompt2model/cli_demo.py", line 435, in <module>
    main()
  File "/Users/gneubig/work/prompt2model/cli_demo.py", line 168, in main
    top_model_name = retriever.retrieve(prompt_spec)
  File "/Users/gneubig/work/prompt2model/prompt2model/model_retriever/description_based_retriever.py", line 277, in retrieve
    model_info = model_name_to_model_info[model_name]
KeyError: 'GuiSales404/e10_lr0.0001'
```

**Comment by neubig** [comment]
Sorry, this was a data error on my side. Closing.
