### ISSUE TITLE
Error when the retrieved dataset's output column is not a string

### ISSUE THREAD

**Issue by viswavi** [neulab/prompt2model#280]
The retrieved dataset's column may be int-valued (e.g. binary integers for classification). Currently, this leads to an error:
```
Traceback (most recent call last):                                                                  
  File "/projects/metis2/users/vijayv/prompt2model/cli_demo.py", line 435, in <module>              
    main()                                                                                          
  File "/projects/metis2/users/vijayv/prompt2model/cli_demo.py", line 367, in main                  
    trained_model, trained_tokenizer = trainer.train_model(                                         
                                       ^^^^^^^^^^^^^^^^^^^^                                         
  File "/projects/metis2/users/vijayv/prompt2model/prompt2model/model_trainer/generate.py", line 304
, in train_model                                                                                    
    concatenated_training_dataset = concatenate_datasets(training_datasets)                         
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                         
  File "/projects/metis0_ssd/users/vijayv/anaconda3/envs/prompt2model/lib/python3.11/site-packages/d
atasets/combine.py", line 182, in concatenate_datasets                                              
    return _concatenate_map_style_datasets(dsets, info=info, split=split, axis=axis)                
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                
  File "/projects/metis0_ssd/users/vijayv/anaconda3/envs/prompt2model/lib/python3.11/site-packages/d
atasets/arrow_dataset.py", line 5829, in _concatenate_map_style_datasets
    _check_if_features_can_be_aligned([dset.features for dset in dsets])
  File "/projects/metis0_ssd/users/vijayv/anaconda3/envs/prompt2model/lib/python3.11/site-packages/$
atasets/features/features.py", line 2083, in _check_if_features_can_be_aligned
    raise ValueError(
ValueError: The features can't be aligned because the key output_col of features {'input_col': Valu$
(dtype='string', id=None), 'output_col': Value(dtype='int64', id=None), 'model_input': Value(dtype=$
string', id=None), 'model_output': Value(dtype='string', id=None)} has unexpected type - Value(dtyp$
='int64', id=None) (expected either Value(dtype='string', id=None) or Value("null").
```

**Comment by zhaochenyang20** [comment]
Here is the solution:

```
processed_dataset = dataset.map(
    lambda example: post_process_example(
        example, 
        instruction="your_instruction", 
        task_id=0, 
        has_encoder=True, 
        dataset_split="train", 
        eos_token="</s>"
    ),
    remove_columns=['input_col', 'output_col']
)
```

**Comment by neubig** [comment]
I believe this is fixed.
