### ISSUE TITLE
Generate DataSet error

### ISSUE THREAD

**Issue by braveboo** [neulab/prompt2model#338]
**### responses = await chat_api.generate_batch_completion( throw err:**
  File "/Users/didi/miniconda3/envs/pmenv/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [Connect call failed ('199.59.149.232', 443)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/didi/prompt2model-main2/tests/mytest.py", line 17, in <module>
    loop.run_until_complete(getCompletion())
  File "/Users/didi/miniconda3/envs/pmenv/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/didi/prompt2model-main2/tests/mytest.py", line 5, in getCompletion
    response =  await openai.ChatCompletion.acreate(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/didi/miniconda3/envs/pmenv/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/didi/miniconda3/envs/pmenv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/didi/miniconda3/envs/pmenv/lib/python3.11/site-packages/openai/api_requestor.py", line 372, in arequest
    result = await self.arequest_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/didi/miniconda3/envs/pmenv/lib/python3.11/site-packages/openai/api_requestor.py", line 685, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

**### but** 
chat_api.generate_one_completion can get right result

**### who can help me resovle the error?**

**Comment by zhaochenyang20** [comment]
Thx for your feedback. We gonna fix this network error.

**Comment by neubig** [comment]
Hi @braveboo , I think this is probably a network error caused by your network environment. I see that other people had similar issues on other repos, so I think it's not a problem with prompt2model itself. You might reference this thread from Microsoft Semantic Kernel to help solve the issue: https://github.com/microsoft/semantic-kernel/issues/627
